### Create song
POST http://localhost:8800/songs HTTP/1.1
Content-Type: application/json

{}


### Fetch all songs
GET http://localhost:8800/songs HTTP/1.1
Content-Type: application/json


### Fetch song by Id
GET http://localhost:8800/songs/2 HTTP/1.1
Content-Type: application/json


### Update song by Id
PUT http://localhost:8800/songs/2 HTTP/1.1
Content-Type: application/json

{}


### Partial Update song by Id
PATCH http://localhost:8800/songs/2 HTTP/1.1
Content-Type: application/json

{}


### Delete song by Id
DELETE http://localhost:8800/songs/2 HTTP/1.1
Content-Type: application/json